name: Auto Update Servers

on:
  schedule:
    - cron: "*/15 * * * *"  # هر 15 دقیقه اجرا می‌شود
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # گرفتن آخرین نسخه از مخزن
      - uses: actions/checkout@v4

      # نصب Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # نصب Telethon برای fetch.py
      - name: Install dependencies
        run: pip install telethon

      # اجرای fetch.py هوشمند
      - name: Fetch links
        run: python fetch.py

      # ذخیره تغییرات و Push
      - name: Commit updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add servers.txt server_manual.txt
          git commit -m "Auto update servers: $(date)" || echo "No changes"
          git push
