name: Generate User Subscriptions

on:
  push:
    paths:
      - "s1ervers.txt"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate user subscription files
        run: |
          users=("sis.peyman" "karam5" "karam4" "karam3" "Yosefi1" "1Rahmani" "Peyman" "Mitra2" "Maryam" "1M.bin" "Kh.peyman" "Kh.Vahid" "Keyvan" "1Karami" "Hosein" "Foad3" "Foad.ios" "Family" "D.karm" "D.karami.new" "D.ka.new.2" "D.jafr.new" "Brother.sh" "Arshia" "Ahar" "1Afroz" "1Af.2")
          
          for user in "${users[@]}"; do
            cp servers.txt "$user"
          done

      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add $(ls | grep -v "servers.txt")   # همه فایل‌های کاربران اضافه میشن
          git commit -m "Auto update user subscriptions" || echo "No changes"
          git push
