name: Generate User Subscriptions

on:
  push:
    paths:
      - "server.txt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate user subscription files
        run: |
          users=("Peyman" "Maryam" "Hosein")
          
          for user in "${users[@]}"; do
            cp server.txt "$user"
          done

      - name: Commit and push updates
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add Peyman Maryam Hosein
          git commit -m "Auto update user subscriptions" || echo "No changes"
          git push