name: Generate User Subscriptions

on:
  push:
    paths:
      - "servers.txt"
      - "users.txt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate user subscription files
        run: |
          while IFS= read -r user; do
            [ -z "$user" ] && continue
            cp servers.txt "$user"
          done < users.txt

      - name: Commit and push updates
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Auto update user subscriptions" || echo "No changes"
          git push